package com.hit.playpal.home.domain.enums;

public enum CreateGroupChatRoomFailure {
    GROUP_CHAT_ROOM_CREATION_FAILED,
    GROUP_CHAT_ROOM_PROFILE_CREATION_FAILED,
    GROUP_CHAT_ROOM_PROFILE_IMAGE_URI_UPLOAD_FAILED,
    GROUP_CHAT_ROOM_PROFILE_IMAGE_STORE_IN_DB_FAILED,
    UNKNOWN_ERROR,
}
